### ISSUE TITLE
Invalid IP fe80::/64 (Linux 64bit)

### ISSUE THREAD

**Issue by larzconwell** [indutny/vock#4]
I was gonna attempt to fix #2 but I ran into an issue my self :D

When doing `vock create` here's what the error said:

```
%:~ ⵗ vock create                                     
/// Vock - VoIP on node.js ///
Enter your private key password: 

/usr/lib/node_modules/vock/node_modules/nat-upnp/node_modules/ip/lib/ip.js:34
    throw Error('Invalid ip address: ' + ip);
          ^
Error: Invalid ip address: fe80::/64
    at Error (unknown source)
    at Object.toBuffer (/usr/lib/node_modules/vock/node_modules/nat-upnp/node_modules/ip/lib/ip.js:34:11)
    at Object.isEqual (/usr/lib/node_modules/vock/node_modules/nat-upnp/node_modules/ip/lib/ip.js:105:10)
    at Ssdp.parseResponse.local (/usr/lib/node_modules/vock/node_modules/nat-upnp/lib/nat-upnp/ssdp.js:167:17)
    at Array.filter (native)
    at Ssdp.parseResponse (/usr/lib/node_modules/vock/node_modules/nat-upnp/lib/nat-upnp/ssdp.js:158:43)
    at Socket.Ssdp.createSocket.process.nextTick.self._bound (/usr/lib/node_modules/vock/node_modules/nat-upnp/lib/nat-upnp/ssdp.js:99:10)
    at Socket.EventEmitter.emit (events.js:91:17)
    at UDP.onMessage (dgram.js:350:8)
```

I wasn't sure if this was caused because a nat-upnp error or some imput from vock, so I decided to post it here.

Vock version is 0.3.11

**Comment by indutny** [comment]
I suppose you're using linux?

**Comment by larzconwell** [comment]
Yes Linux.

**Comment by indutny** [comment]
Please try upgrading to vock@0.3.12 ! I'll reopen issue if it'll fail again.

**Comment by larzconwell** [comment]
on 0.3.13 same error except this time, the IP is undefined!

**Comment by indutny** [comment]
ok, lets try `vock@0.3.14`

**Comment by larzconwell** [comment]
IP is still undefined.

**Comment by indutny** [comment]
Em... can you post stack trace?

**Comment by larzconwell** [comment]
Here you go: 

```
/// Vock - VoIP on node.js ///
Enter your private key password: 

/usr/lib/node_modules/vock/node_modules/nat-upnp/node_modules/ip/lib/ip.js:34
    throw Error('Invalid ip address: ' + ip);
          ^
Error: Invalid ip address: undefined
    at Error (unknown source)
    at Object.toBuffer (/usr/lib/node_modules/vock/node_modules/nat-upnp/node_modules/ip/lib/ip.js:34:11)
    at Object.mask (/usr/lib/node_modules/vock/node_modules/nat-upnp/node_modules/ip/lib/ip.js:63:13)
    at Ssdp.parseResponse.local (/usr/lib/node_modules/vock/node_modules/nat-upnp/lib/nat-upnp/ssdp.js:180:28)
    at Array.filter (native)
    at Ssdp.parseResponse.local (/usr/lib/node_modules/vock/node_modules/nat-upnp/lib/nat-upnp/ssdp.js:177:40)
    at Array.map (native)
    at Ssdp.parseResponse (/usr/lib/node_modules/vock/node_modules/nat-upnp/lib/nat-upnp/ssdp.js:176:6)
    at Socket.Ssdp.createSocket.process.nextTick.self._bound (/usr/lib/node_modules/vock/node_modules/nat-upnp/lib/nat-upnp/ssdp.js:99:10)
    at Socket.EventEmitter.emit (events.js:91:17)
```

**Comment by indutny** [comment]
Ok, I hope `vock@0.3.15` won't have this issue

**Comment by larzconwell** [comment]
:D It works!

**Comment by indutny** [comment]
Ok, great! Hope you'll enjoy hacking ;)
